name: BabyMemoryGallery
on:
  push:
    branches: [ master ]
  # schedule:
    # - cron: "* */6 * * *"
    # - cron: "* */6 * * *"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests