name: BabyMemoryGallery
on:
  push:
    branches: [ master ]
  # schedule:
    # - cron: "* */6 * * *"
    # - cron: "* */6 * * *"
jobs:
  build:
    runs-on: macos-latest
  steps:
    # - uses: actions/checkout@v2
    - name: Set up Python 3.9
      # uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Test
      run: |
        git config --global user.email 390032295@qq.com
        git config --global user.name donGitHubAction
        echo $(date "+%Y-%m-%d %H:%M:%S") >> test.txt
        git add .
        git commit -m"action:`date`"
        git pull --rebase

    - name: Push changes
      uses: BabyMemoryGallery@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
