name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
		
    - name: Update paper list
      run: |
        echo $(date "+%Y-%m-%d %H:%M:%S") >> test.txt
		
    - name: commit
      run: |
        git config --global user.email 390032295@qq.com
        git config --global user.name donGitHubAction
        git add .
        git commit -m "update" -a
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}