name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        # - 'pypy-3.7' # the latest available version of PyPy that supports Python 3.7
        # - 'pypy-3.7-v7.3.3' # Python 3.7 and PyPy 7.3.3
        - 'pypy-3.8' # the latest available version of PyPy that supports Python 3.8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python my_script.py